### ISSUE TITLE
Atlas

### ISSUE THREAD

**Issue by jdbancal** [dimpase/csdp#2]
Hello,

First, thank you very much for the work you put in this software, I tried to compile csdp previously from the package available on the original website, but it only partially worked. It is very nice to just having to call ./configure, and then everything works fine :-)

So I could very easily compile csdp on my ubuntu machine, however it seems that the produces program doesn't use vectorized linear algebra software (even though they are installed on my machine I believe). Do you know whether it would be possible to automatically detect the Atlas libraries and compile accordingly? This could give a huge advantage in terms of performance!

Thanks!

**Comment by dimpase** [comment]
I wonder if you tried configure options

```
  --with-blas=<lib>       use BLAS library <lib>
  --with-lapack=<lib>     use LAPACK library <lib>
```

which you can see if you run ./configure --help

It should detect some BLAS and LAPACK, and use them, even if you don't specify these options, and fail otherwise. 

You can check the libraries linked using ldd, e.g.

```
  $ ldd /usr/local/lib/libsdp.so
linux-vdso.so.1 =>  (0x00007ffdcdf49000)
liblapack.so.3 => /usr/lib/liblapack.so.3 (0x00007fb83c9a3000)
libblas.so.3 => /usr/lib/libblas.so.3 (0x00007fb83c3d7000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb83c0d1000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb83bd0c000)
libgfortran.so.3 => /usr/lib/x86_64-linux-gnu/libgfortran.so.3 (0x00007fb83b9f2000)
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb83b7dc000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb83b5be000)
/lib64/ld-linux-x86-64.so.2 (0x00007fb83d357000)
libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007fb83b382000)
```

So you see that "standard" liblapack and libblas are being used on my Ubuntu 14.04 system. I used
./configure without any options, and then ran `make` and `sudo make install`

**Comment by dimpase** [comment]
And upon installing `libopenblas-dev`, I get

```
 $ ldd /usr/local/lib/libsdp.so
linux-vdso.so.1 =>  (0x00007fffcb973000)
liblapack.so.3 => /usr/lib/liblapack.so.3 (0x00007f5ef0353000)
libopenblas.so.0 => /usr/lib/libopenblas.so.0 (0x00007f5eeeb4a000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5eee844000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5eee47f000)
libblas.so.3 => /usr/lib/libblas.so.3 (0x00007f5eecc76000)
libgfortran.so.3 => /usr/lib/x86_64-linux-gnu/libgfortran.so.3 (0x00007f5eec95c000)
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5eec746000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5eec528000)
/lib64/ld-linux-x86-64.so.2 (0x00007f5ef0d07000)
libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f5eec2ec000)
```

so `openblas` was automatically picked. And if installed in Sagemath, it gets linked with Atlas just fine.
